display_information:
  name: Gidipex Support
  description: Chatwoot integration for Gidipex support
  background_color: "#1F93FF"
features:
  bot_user:
    display_name: Gidipex Support
    always_online: true
oauth_config:
  redirect_urls:
    - https://support.gidipex.com/omniauth/slack/callback
  scopes:
    bot:
      - commands
      - chat:write
      - channels:read
      - channels:join
      - channels:manage
      - channels:history
      - groups:read
      - groups:history
      - im:read
      - im:write
      - im:history
      - mpim:read
      - mpim:history
      - users:read
      - users:read.email
      - files:read
      - files:write
      - links:read
      - links:write
settings:
  event_subscriptions:
    request_url: https://support.gidipex.com/webhooks/slack
    bot_events:
      - message.channels
      - message.groups
      - message.im
      - message.mpim
      - link_shared
  interactivity:
    is_enabled: true
    request_url: https://support.gidipex.com/webhooks/slack
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
